name: 灵鹿直播源自动更新
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requests
        run: pip install requests
      - name: Run script
        run: python main.py
      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: 自动更新直播源
          add: result.txt
